export const bondingSeedData = [
    // SPIRITUAL (25)
    { title: "Shalat Tahajud Bersama", description: "Bisa 2 rakaat saja, lalu berdoa bersama.", category: "SPIRITUAL" },
    { title: "Tilawah Bergantian", description: "Membaca Al-Quran 1 halaman bergantian dengan pasangan.", category: "SPIRITUAL" },
    { title: "Saling Mendoakan Terdengar", description: "Saling mendoakan dengan suara yang bisa didengar pasangan setelah shalat.", category: "SPIRITUAL" },
    { title: "Puasa Sunnah Bareng", description: "Puasa Senin-Kamis atau Ayyamul Bidh bersama.", category: "SPIRITUAL" },
    { title: "Kajian Bareng", description: "Duduk bersama menonton/mendengarkan 1 kajian pendek (min 15 menit).", category: "SPIRITUAL" },
    { title: "Sedekah Atas Nama Berdua", description: "Menyalurkan sedekah niat berdua untuk keluarga tercinta.", category: "SPIRITUAL" },
    { title: "Murojaah Hafalan Surah", description: "Saling menyimak hafalan surah-surah pendek.", category: "SPIRITUAL" },
    { title: "Zikir Pagi Petang Bareng", description: "Duduk berdampingan membaca Al-Matsurat atau zikir pagi/petang.", category: "SPIRITUAL" },
    { title: "Mengingatkan Berwudhu Sebelum Tidur", description: "Mengajak dan memastikan pasangan wudhu sebelum tidur.", category: "SPIRITUAL" },
    { title: "Bertanya Kisah Nabi", description: "Saling melempar kuis / menceritakan satu kisah Nabi.", category: "SPIRITUAL" },
    { title: "Membaca Buku Agama Bersama", description: "Membahas 1 bab/pasal dari buku pernikahan/agama.", category: "SPIRITUAL" },
    { title: "Minta Maaf Sebelum Tidur", description: "Saling bermaafan khusus atas khilaf hari ini.", category: "SPIRITUAL" },
    { title: "Mendengarkan Murottal di Perjalanan", description: "Menyetel murottal favorit berdua di kendaraan.", category: "SPIRITUAL" },
    { title: "Shalat Jamaah di Rumah", description: "Minimal shalat Maghrib/Isya berjamaah (jika suami tidak ke masjid krn udzur/sunnah).", category: "SPIRITUAL" },
    { title: "Berdua Menengok Orang Sakit", description: "Mengunjungi kerabat/tetangga yang sedang sakit berdua.", category: "SPIRITUAL" },
    { title: "Mendoakan Mertua", description: "Secara sadar menyebut nama mertua dalam doa harian.", category: "SPIRITUAL" },
    { title: "Tadarusan Malam", description: "Menghidupkan malam walau 15 menit dengan tilawah bersama.", category: "SPIRITUAL" },
    { title: "Berbagi Hikmah Shalat Jumat/Kajian", description: "Suami menceritakan isi khutbah/kajian kepada istri.", category: "SPIRITUAL" },
    { title: "Membaca Surat Al-Mulk", description: "Membaca bersama sebelum beranjak tidur.", category: "SPIRITUAL" },
    { title: "Mengingatkan Shalat Dhuha", description: "Saling mengingatkan via WA waktu shalat Dhuha.", category: "SPIRITUAL" },
    { title: "Membeli Buku Doa/Zikir Baru", description: "Membeli atau mendownload PDF buku doa baru untuk dipelajari.", category: "SPIRITUAL" },
    { title: "Hafalan Doa Sehari-hari", description: "Mengecek hafalan doa (misal: doa masuk pasar, doa keluar rumah).", category: "SPIRITUAL" },
    { title: "Beristighfar 100x Bersama", description: "Duduk sejenak bersama mengucapkan istighfar 100x.", category: "SPIRITUAL" },
    { title: "Merutinkan Shalawat", description: "Membaca shalawat minimal 10x bersama setelah shalat.", category: "SPIRITUAL" },
    { title: "Merencanakan Umrah/Haji", description: "Duduk membicarakan mimpi dan menabung untuk Umrah berdua.", category: "SPIRITUAL" },

    // DEEP_TALK (25)
    { title: "Tanya: Apa Ketakutan Terbesarmu?", description: "Bahas tuntas ketakutan terbesar tahun ini tanpa menghakimi.", category: "DEEP_TALK" },
    { title: "Tulis Surat Cinta Fisik", description: "Tulis di kertas, sembunyikan di saku/dompet pasangan.", category: "DEEP_TALK" },
    { title: "Memuji 3 Hal Spesifik", description: "Puji 3 hal spesifik mengenai fisik atau sifatnya sebelum tidur.", category: "DEEP_TALK" },
    { title: "Evaluasi Visi Pernikahan", description: "Bahas kembali: 'Apakah tujuan awal nikah kita sudah berjalan on-track?'", category: "DEEP_TALK" },
    { title: "Mengingat Masa Taaruf/Mulai Kenal", description: "Ceritakan hal paling berkesan saat pertama kali ingin menikah.", category: "DEEP_TALK" },
    { title: "Bahas Harapan Pola Asuh Anak", description: "Diskusi cara mendidik anak sesuai sunnah dan pembagian peran.", category: "DEEP_TALK" },
    { title: "Apresiasi Kebiasaan Kecil", description: "Sebutkan 1 kebiasaan remeh pasangan yang diam-diam kamu syukuri.", category: "DEEP_TALK" },
    { title: "Apa yang Harus Ku-Kurangi?", description: "Saling bertanya satu kebiasaan buruk yang ingin pasangan ubah.", category: "DEEP_TALK" },
    { title: "Bahasa Cinta Utama", description: "Identifikasi ulang 'Love Language' masing-masing (waktu, kata, sentuhan, hadiah, pelayanan).", category: "DEEP_TALK" },
    { title: "Rencana Keuangan Terbuka", description: "Bahas target tabungan dan cicilan tanpa menutupi hutang/pengeluaran.", category: "DEEP_TALK" },
    { title: "Diskusi Kesiapan Kematian", description: "Membahas pesan-pesan penting jika salah satu dipanggil lebih dulu.", category: "DEEP_TALK" },
    { title: "Review Kemesraan Minggu Ini", description: "Grade 1-10 level keromantisan minggu ini, dan apa yang bisa diperbaiki.", category: "DEEP_TALK" },
    { title: "Membahas Rencana 5 Tahun Kedepan", description: "Dimana kita akan tinggal? Pekerjaan seperti apa? Gambarkan visinya.", category: "DEEP_TALK" },
    { title: "Bedah Buku/Podcast Parenting", description: "Dengarkan/baca satu bahasan dan bahas relevansinya dengan anak sendiri.", category: "DEEP_TALK" },
    { title: "Tanya: Apa Impian Pribadimu?", description: "Dukung hobi atau ambisi karir halal pasangan.", category: "DEEP_TALK" },
    { title: "Berterima Kasih atas Pengorbanan", description: "Secara spesifik hargai lelah suami kerja atau lelah istri urus rumah/anak.", category: "DEEP_TALK" },
    { title: "Menonton Album Foto Lama", description: "Lihat galeri 3 tahun lalu dan ceritakan kesannya.", category: "DEEP_TALK" },
    { title: "Bertanya: Apa yang Membuatmu Stres?", description: "Dengarkan berkeluh kesah tanpa langsung memberi solusi (kecuali diminta).", category: "DEEP_TALK" },
    { title: "Pujian di Depan Anak", description: "Puji pasangan di depan anak (misal: 'Masakan Ummi enak ya nak?').", category: "DEEP_TALK" },
    { title: "Hal yang Paling Dibanggakan", description: "Beritahu pasangan hal apa dari dirinya yang membuatmu bangga jadi pasangannya.", category: "DEEP_TALK" },
    { title: "Diskusi Cara Menanggapi Konflik", description: "Sepakati aturan bertengkar (misal: tidak boleh main fisik, tidak boleh sebut cerai).", category: "DEEP_TALK" },
    { title: "Merangkum Hal Positif Hari Ini", description: "Sebutkan bergantian 3 hal baik yang terjadi hari ini.", category: "DEEP_TALK" },
    { title: "Membahas Masa Tua", description: "Bercerita ingin seperti apa nanti saat rambut sudah memutih semua.", category: "DEEP_TALK" },
    { title: "Bertanya Tentang Kebersamaan Keluarga Besar", description: "Bahas cara merawat hubungan baik dengan mertua & ipar.", category: "DEEP_TALK" },
    { title: "Silent Time / Eye Contact", description: "Saling tatap tanpa ngobrol selama 3 menit penuh.", category: "DEEP_TALK" },

    // SERVICE (25)
    { title: "Suami Memasak Makanan Kesukaan Istri", description: "Bisa menu sederhana asal hasil masakan sendiri.", category: "SERVICE" },
    { title: "Pijat Punggung/Kaki 15 Menit", description: "Gantian memberikan pijatan relaksasi.", category: "SERVICE" },
    { title: "Cuci Piring Bersama", description: "Habis makan, bereskan meja dan cuci piring berdua tanpa HP.", category: "SERVICE" },
    { title: "Menyiapkan Minuman Hangat", description: "Buatkan kopi/teh/susu tanpa diminta saat malam/pagi hari.", category: "SERVICE" },
    { title: "Mengambil Alih Shift Anak", description: "Beri waktu 'Me Time' 2 jam untuk pasangan, ambil alih urus anak.", category: "SERVICE" },
    { title: "Merapikan Tempat Tidur", description: "Siapa bangun belakangan wajib merapikan ranjang.", category: "SERVICE" },
    { title: "Mencium Kening Sebelum Berangkat", description: "Jadikan ritual wajib sebelum salah satu keluar rumah.", category: "SERVICE" },
    { title: "Memotong Kuku Pasangan", description: "Tawarkan diri memotong kuku tangannya (sunnah Jumat).", category: "SERVICE" },
    { title: "Menyiapkan Pakaian Kerja", description: "Pilihkan dan setrika/siapkan baju kerjanya besok.", category: "SERVICE" },
    { title: "Memberi Kejutan Kecil", description: "Beli cemilan ringan favoritnya di jalan pulang.", category: "SERVICE" },
    { title: "Membersihkan Kendaraan Bersama", description: "Cuci mobil/motor berdua di hari minggu.", category: "SERVICE" },
    { title: "Membuang Sampah Rumah", description: "Inisiatif buang sampah sebelum diminta.", category: "SERVICE" },
    { title: "Sisir Rambut Pasangan", description: "Sisir/usap lembut rambut pasangan sebelum tidur.", category: "SERVICE" },
    { title: "Menjaga Privasi HP", description: "Sengaja menaruh HP jauh di meja saat sedang makan malam/ngomong berdua.", category: "SERVICE" },
    { title: "Charge HP Pasangan", description: "Melihat baterai pasangan mau habis, bantu colokkan chargernya.", category: "SERVICE" },
    { title: "Isikan Bensin Kendaraan", description: "Bawa motor/mobil istri untuk diisikan bensin full tank.", category: "SERVICE" },
    { title: "Pujian Spontan", description: "Puji wangi/penampilan tanpa aba-aba.", category: "SERVICE" },
    { title: "Bantu Tugas Paling Dibenci", description: "Kerjakan chore yang paling tidak disukai pasangan (misal: sikat WC).", category: "SERVICE" },
    { title: "Bukakan Pintu Kendaraan", description: "Praktekkan adab romantis membuka pintu saat naik/turun.", category: "SERVICE" },
    { title: "Saling Menyuapi saat Makan", description: "Beri 1-2 suapan saat sedang makan berdua.", category: "SERVICE" },
    { title: "Membawa Bekal Makan", description: "Suami membawa bekal masakan istri ke kantor/tempat kerja.", category: "SERVICE" },
    { title: "Mengenakan Pakaian Terbaik di Rumah", description: "Berdandan/wangi khusus saat berduaan di kamar (bukan cuma saat keluar).", category: "SERVICE" },
    { title: "Memijat Kepala saat Pasangan Lelah", description: "Spontan tekan-tekan dahi/kepala jika pasangan terlihat stres.", category: "SERVICE" },
    { title: "Belikan Barang Kebutuhan Personal", description: "Beli sabun/skincare/silet cukur yang pasangan butuhkan.", category: "SERVICE" },
    { title: "Kirim Chat Manis Singkat di Tengah Hari", description: "Cukup 'Lagi ngapain sayang? Jangan lupa makan ya'.", category: "SERVICE" },

    // FUN (25)
    { title: "Jalan Santai Keliling Komplek", description: "Meninggalkan HP di rumah, jalan santai 15 menit.", category: "FUN" },
    { title: "Kencan di Teras Malam Hari", description: "Setelah anak tidur, duduk di teras/balkon minum teh ngobrol santai.", category: "FUN" },
    { title: "Menonton Foto Pernikahan", description: "Nostalgia buka video/foto pernikahan kalian.", category: "FUN" },
    { title: "Pajang Foto Baru Berdua", description: "Selfie berdua, lalu print/jadikan wallpaper.", category: "FUN" },
    { title: "Jalan-jalan Tanpa Tujuan (Riding)", description: "Naik motor/mobil muter-muter aja 30 menit sambil ngobrol.", category: "FUN" },
    { title: "Nonton Film Bareng", description: "Satu judul film keluarga/documenter Islami/movie santai di rumah.", category: "FUN" },
    { title: "Lomba Masak Simple", description: "Siapa yang bikin mie goreng paling enak.", category: "FUN" },
    { title: "Main Game Berdua", description: "Board game, kartu, tebak-tebakan, atau game konsol.", category: "FUN" },
    { title: "Pergi Jajan ke Minimarket Malam", description: "Anggap kayak anak ABG pacaran (halal) beli eskrim dobel.", category: "FUN" },
    { title: "Staycation Murah Meriah", description: "Walau budget pas, coba nginep 1 malam di hotel budjet / tata kamar layaknya hotel.", category: "FUN" },
    { title: "Rekam Video Lucu Berdua", description: "Pakai filter lucu di medsos untuk arsip pribadi.", category: "FUN" },
    { title: "Olahraga Bareng", description: "Jogging pagi, senam indoor, atau bersepeda berdua.", category: "FUN" },
    { title: "Eksplorasi Kuliner Baru", description: "Coba makan di tempat jauh atau random yang belum pernah dicoba.", category: "FUN" },
    { title: "Berkebun Cepat", description: "Tanam 1 bibit bunga/herba baru di pot.", category: "FUN" },
    { title: "Perang Bantal / Gelitik-gelitikan", description: "Bercanda fisik kayak anak kecil.", category: "FUN" },
    { title: "Buat Julukan Sayang Baru", description: "Panggil dengan nama manja/Arab yang belum pernah dipakai.", category: "FUN" },
    { title: "Pergi Makan Tanpa Anak (Jarang-jarang)", description: "Titip anak max 2 jam, makan berdua saja ngobrol fokus.", category: "FUN" },
    { title: "Tebak Makanan Mata Tertutup", description: "Suapi cemilan dan suruh tebak rasanya.", category: "FUN" },
    { title: "Karaoke Shalawat / Nasyid", description: "Nyanyi bareng nasyid romantis atau senandung religi.", category: "FUN" },
    { title: "Gombal Secara Tiba-tiba", description: "Cari pantun/gombalan receh dan sampaikan dg percaya diri.", category: "FUN" },
    { title: "Bikin Playlist Lagu Berdua", description: "Kumpulkan 10 lagu fav kalian berdua di Spotify/Youtube.", category: "FUN" },
    { title: "Membuat Karya Seni (DIY)", description: "Cat barang bekas bareng, atau prakarya untuk kamar.", category: "FUN" },
    { title: "Spa / Luluran di Rumah", description: "Pake masker wajah / spa sederhana berduaan.", category: "FUN" },
    { title: "Buka Puasa di Luar Berdua", description: "Kalau lagi Shaum sunnah, spesial niatkan ifthar berdua sesekali.", category: "FUN" },
    { title: "Baca Buku Cerita Lucu Bersama", description: "Gantian baca komik / cerita ngakak 1 chap.", category: "FUN" }
];
