export const bondingFamilySeedData = [
    // SPIRITUAL (25)
    { title: "Shalat Jamaah Sekeluarga", description: "Shalat Maghrib atau Isya berjamaah di rumah bersama ayah, bunda, dan anak-anak.", category: "SPIRITUAL" },
    { title: "Kultum Singkat Bergiliran", description: "Setelah shalat, salah satu anggota keluarga memberikan nasihat singkat 3-5 menit.", category: "SPIRITUAL" },
    { title: "Hafalan Bersama di Ruang Tengah", description: "Duduk melingkar dan menyimak hafalan surah pendek anak-anak.", category: "SPIRITUAL" },
    { title: "Doa Bersama Berkeliling", description: "Setiap anggota keluarga menyebutkan satu doa yang diinginkan, diamini bersama.", category: "SPIRITUAL" },
    { title: "Membaca Al-Kahfi di Malam Jumat", description: "Membaca bersama-sama atau bergiliran beberapa ayat.", category: "SPIRITUAL" },
    { title: "Sedekah Berjamaah", description: "Mengumpulkan uang receh dari setiap anggota keluarga untuk disumbangkan.", category: "SPIRITUAL" },
    { title: "Menonton Kisah Nabi untuk Anak", description: "Menonton animasi kisah Nabi bersama dan mendiskusikan hikmahnya.", category: "SPIRITUAL" },
    { title: "Zikir Pagi Bersama", description: "Duduk bersama setelah Subuh membaca zikir pagi.", category: "SPIRITUAL" },
    { title: "Lomba Adan/Iqamah di Rumah", description: "Anak laki-laki berlatih adzan dan iqamah dengan bimbingan Ayah.", category: "SPIRITUAL" },
    { title: "Membaca Buku Sirah Nabawiyah", description: "Bunda membacakan satu bab sirah nabawiyah untuk anak-anak.", category: "SPIRITUAL" },
    { title: "Mengenal Asmaul Husna", description: "Menghafal 3 nama Allah baru setiap minggu bersama-sama.", category: "SPIRITUAL" },
    { title: "Berwudhu Tertib", description: "Ayah/Bunda mengawasi dan mengajarkan tata cara wudhu yang sempurna.", category: "SPIRITUAL" },
    { title: "Puasa Sunnah Latihan", description: "Mengajak anak-anak yang sudah mampu untuk ikut puasa sunnah setengah hari.", category: "SPIRITUAL" },
    { title: "Mempraktikkan Adab Makan", description: "Makan bersama sambil mempraktikkan doa dan adab makan sesuai sunnah.", category: "SPIRITUAL" },
    { title: "Saling Memaafkan Sebelum Tidur", description: "Seluruh anggota keluarga berkumpul untuk saling meminta maaf.", category: "SPIRITUAL" },
    { title: "Menghias Sudut Shalat", description: "Bersama-sama merapikan dan menghias tempat shalat di rumah.", category: "SPIRITUAL" },
    { title: "Belajar Makna Bacaan Shalat", description: "Membahas arti satu bacaan shalat (misal: Al-Fatihah).", category: "SPIRITUAL" },
    { title: "Mendengar Murottal Saat Santai", description: "Memutar murottal di ruang keluarga tanpa distraksi gadget.", category: "SPIRITUAL" },
    { title: "Mengingatkan Zikir Masuk Kamar Mandi", description: "Saling mengingatkan doa masuk/keluar kamar mandi.", category: "SPIRITUAL" },
    { title: "Menelepon Kakek/Nenek Bersama", description: "Menyambung silaturahmi dan meminta doa dari orang tua.", category: "SPIRITUAL" },
    { title: "Belajar Tata Cara Tayammum", description: "Simulasi cara bertayammum jika tidak ada air.", category: "SPIRITUAL" },
    { title: "Membahas Hadits Pendek", description: "Membaca satu hadits dari Arbain Nawawi dan mendiskusikannya.", category: "SPIRITUAL" },
    { title: "Berdiskusi Tentang Surga", description: "Membayangkan keindahan surga bersama anak-anak untuk motivasi ibadah.", category: "SPIRITUAL" },
    { title: "Evaluasi Ibadah Mingguan", description: "Bicara santai tentang shalat 5 waktu minggu ini.", category: "SPIRITUAL" },
    { title: "Menulis Target Ibadah Ramadhan", description: "Membuat poster target ibadah untuk ditempel di dinding.", category: "SPIRITUAL" },

    // DEEP_TALK (25)
    { title: "Lingkaran Cerita Hari Ini", description: "Setiap orang menceritakan satu hal paling bahagia hari ini.", category: "DEEP_TALK" },
    { title: "Tanya Anak: Apa Cita-citamu?", description: "Mendengarkan impian anak dan bagaimana mereka ingin mencapainya.", category: "DEEP_TALK" },
    { title: "Bahas Visi Keluarga", description: "Menjelaskan kepada anak-anak apa tujuan keluarga kita.", category: "DEEP_TALK" },
    { title: "Apresiasi Kebaikan Anak", description: "Ayah/Bunda menyebutkan satu sifat baik anak secara spesifik.", category: "DEEP_TALK" },
    { title: "Bertanya: Apa yang Membuatmu Sedih?", description: "Mendengarkan perasaan anak tanpa langsung menasihati.", category: "DEEP_TALK" },
    { title: "Diskusi Tentang Kejujuran", description: "Membahas mengapa jujur itu penting dalam keluarga.", category: "DEEP_TALK" },
    { title: "Cerita Masa Kecil Ayah/Bunda", description: "Ayah/Bunda menceritakan pengalaman lucu saat masih kecil.", category: "DEEP_TALK" },
    { title: "Harapan Anak Kepada Orang Tua", description: "Mendengarkan apa yang anak inginkan dari Ayah/Bunda.", category: "DEEP_TALK" },
    { title: "Membahas Cara Menyelesaikan Konflik", description: "Bicara tentang apa yang harus dilakukan jika adik-kakak bertengkar.", category: "DEEP_TALK" },
    { title: "Tanya: Siapa Teman Terbaikmu?", description: "Mengenal lingkungan pertemanan anak dengan cara yang asyik.", category: "DEEP_TALK" },
    { title: "Diskusi Tentang Rasa Syukur", description: "Setiap orang menyebutkan 3 nikmat Allah hari ini.", category: "DEEP_TALK" },
    { title: "Apa yang Ingin Kamu Pelajari?", description: "Mendukung minat atau hobi baru yang ingin ditekuni anak.", category: "DEEP_TALK" },
    { title: "Bicara Tentang Adab Kepada Orang Tua", description: "Mengingatkan kembali pentingnya berkata 'Ah' pun tidak boleh.", category: "DEEP_TALK" },
    { title: "Harapan Orang Tua Kepada Anak", description: "Menyampaikan doa dan harapan dengan cara yang lembut.", category: "DEEP_TALK" },
    { title: "Review Aturan Rumah Bersama", description: "Diskusi tentang jam tidur, waktu main gadget, dll.", category: "DEEP_TALK" },
    { title: "Tanya: Apa Hal Terlucu Hari Ini?", description: "Tertawa bersama menceritakan kejadian konyol.", category: "DEEP_TALK" },
    { title: "Diskusi Tentang Membantu Sesama", description: "Membahas bagaimana tetangga atau teman yang butuh bantuan.", category: "DEEP_TALK" },
    { title: "Apa yang Kamu Lakukan Jika Marah?", description: "Mengajarkan cara mengelola emosi sesuai sunnah (wudhu/diam).", category: "DEEP_TALK" },
    { title: "Bicara Tentang Keamanan Diri", description: "Edukasi anak tentang sentuhan boleh dan tidak boleh.", category: "DEEP_TALK" },
    { title: "Evaluasi Komunikasi Keluarga", description: "Apakah kita sudah cukup sering mengobrol minggu ini?", category: "DEEP_TALK" },
    { title: "Membahas Tokoh Heroik Islam", description: "Menceritakan keberanian sahabat Nabi dalam membela agama.", category: "DEEP_TALK" },
    { title: "Tanya Anak: Apa Ketakutanmu?", description: "Membantu anak menghadapi rasa takutnya.", category: "DEEP_TALK" },
    { title: "Diskusi Tentang Menabung", description: "Mengajarkan konsep hemat dan manfaat menabung sejak dini.", category: "DEEP_TALK" },
    { title: "Harapan Untuk Masa Depan Keluarga", description: "Berkhayal positif tentang 10 tahun kedepan.", category: "DEEP_TALK" },
    { title: "Waktu Tanpa Gadget", description: "Satu jam tanpa HP/TV, fokus hanya mengobrol.", category: "DEEP_TALK" },

    // SERVICE (25)
    { title: "Kerja Bakti Bersihkan Rumah", description: "Setiap anggota keluarga punya tugas masing-masing.", category: "SERVICE" },
    { title: "Masak Makan Siang Bersama", description: "Anak-anak membantu memotong sayur atau menyiapkan meja.", category: "SERVICE" },
    { title: "Membantu Tugas Kakak/Adik", description: "Kakak membantu adik belajar atau sebaliknya.", category: "SERVICE" },
    { title: "Mencuci Motor/Mobil Bersama", description: "Main air sambil membersihkan kendaraan Ayah.", category: "SERVICE" },
    { title: "Menyiapkan Hidangan Untuk Ayah", description: "Bunda dan anak-anak membuatkan minuman spesial saat Ayah pulang.", category: "SERVICE" },
    { title: "Merapikan Rak Buku Sekeluarga", description: "Menatanya kembali berdasarkan kategori atau warna.", category: "SERVICE" },
    { title: "Membersihkan Taman/Halaman", description: "Mencabut rumput liar atau menyiram tanaman bersama.", category: "SERVICE" },
    { title: "Menyiapkan Sarapan Sederhana", description: "Anak-anak mencoba menyiapkan roti atau sereal sendiri.", category: "SERVICE" },
    { title: "Membantu Bunda Lipat Baju", description: "Anak-anak belajar melipat pakaian mereka sendiri.", category: "SERVICE" },
    { title: "Operasi Semut di Ruang Tamu", description: "Mencari debu dan kotoran kecil selama 10 menit.", category: "SERVICE" },
    { title: "Menyiapkan Perlengkapan Shalat", description: "Menata sajadah dan mukena untuk shalat jamaah.", category: "SERVICE" },
    { title: "Membuang Sampah Berjamaah", description: "Semua tempat sampah di rumah dikosongkan bersama.", category: "SERVICE" },
    { title: "Membantu Belanja ke Pasar/Minimarket", description: "Anak memegang daftar belanjaan dan mencarinya.", category: "SERVICE" },
    { title: "Menata Meja Makan Estetik", description: "Mengatur piring dan gelas secantik mungkin.", category: "SERVICE" },
    { title: "Membantu Ayah Berkebun", description: "Menanam bibit baru atau memberi pupuk.", category: "SERVICE" },
    { title: "Membersihkan Kaca Jendela", description: "Tugas seru dengan semprotan air dan lap.", category: "SERVICE" },
    { title: "Menyikat Kamar Mandi Bersama", description: "Tugas berat yang jadi ringan jika dilakukan bersama.", category: "SERVICE" },
    { title: "Merapikan Mainan Setelah Selesai", description: "Komitmen semua anak untuk membereskan mainannya.", category: "SERVICE" },
    { title: "Menghias Kamar Anak", description: "Menata ulang letak meja belajar atau bantal.", category: "SERVICE" },
    { title: "Membantu Tetangga", description: "Mengirimkan makanan atau membantu hal kecil lainnya.", category: "SERVICE" },
    { title: "Mencuci Sepatu Sekolah Bersama", description: "Kegiatan rutin di hari Minggu pagi.", category: "SERVICE" },
    { title: "Menyiapkan Minum Saat Ada Tamu", description: "Melatih adab memuliakan tamu bagi anak-anak.", category: "SERVICE" },
    { title: "Merapikan Kabel-kabel di Rumah", description: "Memastikan tidak ada kabel yang berantakan demi keamanan.", category: "SERVICE" },
    { title: "Menyortir Mainan Tak Terpakai", description: "Untuk disumbangkan kepada yang membutuhkan.", category: "SERVICE" },
    { title: "Menyiapkan Perlengkapan Esok Hari", description: "Tas sekolah, baju kerja, dll disiapkan malam ini.", category: "SERVICE" },

    // FUN (25)
    { title: "Piknik di Ruang Tamu", description: "Gelar tikar, makan camilan bersama tanpa gadget.", category: "FUN" },
    { title: "Permainan Tradisional", description: "Main petak umpet, bentengan, atau dakon di rumah.", category: "FUN" },
    { title: "Olahraga Pagi Sekeluarga", description: "Senam bersama atau jalan santai keliling komplek.", category: "FUN" },
    { title: "Nonton Film Keluarga", description: "Pilih satu film yang bisa dinikmati semua usia.", category: "FUN" },
    { title: "Lomba Mewarnai/Menggambar", description: "Tema bebas, yang penting semua ikut berpartisipasi.", category: "FUN" },
    { title: "Tebak Kata Gaya (Charades)", description: "Satu orang bergaya, yang lain menebak.", category: "FUN" },
    { title: "Bernyanyi Lagu Anak/Religi", description: "Menggunakan alat musik sederhana atau tepuk tangan.", category: "FUN" },
    { title: "Membuat Kue Bersama", description: "Menghias donat atau mencetak kue kering.", category: "FUN" },
    { title: "Membangun Tenda di Dalam Rumah", description: "Gunakan selimut dan kursi untuk membuat markas.", category: "FUN" },
    { title: "Lomba Estafet Sederhana", description: "Memindahkan air atau kelereng di halaman.", category: "FUN" },
    { title: "Foto Keluarga Bertema", description: "Pakai baju warna senada dan berfoto bersama.", category: "FUN" },
    { title: "Main Puzzle Besar", description: "Menyusun puzzle ratusan keping bersama-sama.", category: "FUN" },
    { title: "Camping di Halaman Belakang", description: "Jika ada area, pasang tenda sungguhan.", category: "FUN" },
    { title: "Eksperimen Sains Sederhana", description: "Membuat gunung merapi dari baking soda, dll.", category: "FUN" },
    { title: "Perjalanan Misterius", description: "Ayah menyetir ke tempat rahasia, anak menebak tujuannya.", category: "FUN" },
    { title: "Mencari Harta Karun", description: "Bunda menyembunyikan hadiah, anak mencari dengan petunjuk.", category: "FUN" },
    { title: "Pertunjukan Bakat Keluarga", description: "Anak baca puisi, Ayah sulap, Bunda dongeng.", category: "FUN" },
    { title: "Membuat Video Dokumenter Keluarga", description: "Wawancara setiap anggota keluarga tentang perasaannya.", category: "FUN" },
    { title: "Main Lego/Blok Bersama", description: "Membangun kota impian dari balok susun.", category: "FUN" },
    { title: "Jalan Ke Toko Buku Bersama", description: "Masing-masing boleh pilih satu buku favorit.", category: "FUN" },
    { title: "Makan Malam di Luar", description: "Mencoba tempat baru yang ramah anak.", category: "FUN" },
    { title: "Lomba Makan Kerupuk", description: "Main game seru-seruan di halaman rumah.", category: "FUN" },
    { title: "Tukar Kado Sederhana", description: "Barang tidak harus mahal, yang penting niatnya.", category: "FUN" },
    { title: "Main Air di Halaman", description: "Pake kolam karet atau selang, seru-seruan bareng.", category: "FUN" },
    { title: "Belanja Bahan Masakan Bareng", description: "Di pasar tradisional agar anak kenal pedagang.", category: "FUN" }
];
